export const ProjectsData = [
    {
        id: '1',
        img: '../image/prj/prj01.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img01.jpg',
        imgCarousel2: 'image/room/img02.jpg',
        imgCarousel3: 'image/room/img03.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'

    },
    {
        id: '2',
        img: 'image/prj/prj02.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img01.jpg',
        imgCarousel2: 'image/room/img02.jpg',
        imgCarousel3: 'image/room/img04.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'
    },
    {
        id: '3',
        img: 'image/prj/prj03.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img01.jpg',
        imgCarousel2: 'image/room/img05.jpg',
        imgCarousel3: 'image/room/img02.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'
    },
    {
        id: '4',
        img: 'image/prj/prj04.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img06.jpg',
        imgCarousel2: 'image/room/img07.jpg',
        imgCarousel3: 'image/room/img08.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'
    },
    {
        id: '5',
        img: 'image/prj/prj05.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img01.jpg',
        imgCarousel2: 'image/room/img02.jpg',
        imgCarousel3: 'image/room/img01.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'
    },
    {
        id: '6',
        img: 'image/prj/prj06.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img01.jpg',
        imgCarousel2: 'image/room/img02.jpg',
        imgCarousel3: 'image/room/img08.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'
    },
    {
        id: '7',
        img: 'image/prj/prj07.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img01.jpg',
        imgCarousel2: 'image/room/img02.jpg',
        imgCarousel3: 'image/room/img01.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'
    },
    {
        id: '8',
        img: 'image/prj/prj08.jpg',
        name: 'The Aston Vill Hotel',
        feedback: 5.0,
        adr: 'Alice Springs NT 0870, Australia',
        cost: 200.7,
        imgCarousel: 'image/room/img01.jpg',
        imgCarousel2: 'image/room/img02.jpg',
        imgCarousel3: 'image/room/img01.jpg',
        desribe0: 'With the beautiful landscape of the city at night, you will see the whole city with lights and chill music giving you relaxation and lightness in your soul. Coming to us, you will fully enjoy it. vacation with perfect services.',
        describe0service:' Buffet breakfast, Mineral water in the room, Wireless Internet service (wifi)',
        describe0chkout:'12:00 daily',
        desribe0pay:' Cash (VND, USD, EURO, ...) Visa and Master credit cards',
        desribe1: 'Liên hệ hotline: 1900 6750 để nhận được ưu đãi đặt phòng sớm nhất !'
    },
]